Allow mig to build as C23
Autoconf 2.73 insists on building C source in C23 mode, such as via
-std=gnu23, if it detected a C compiler capable of this language
standard. This occurs regardless of whether the code being compiled
expects or wants to be built as C23.

mig did not build as C23 because it has variables named `bool`, and
`bool` is a reserved word in C23. It’s possible to disable this autoconf
behavior, but it’s fiddly, and it’s easy enough to change the variable
names in mig.

Fixes compile errors such as:

```
In file included from string.c:53:
./strdefs.h:89:33: error: cannot combine with previous
      'type-name' declaration specifier
   89 | extern char *strbool( boolean_t bool );
      |                                 ^
string.c:103:19: error: cannot combine with previous
      'type-name' declaration specifier
  103 | strbool(boolean_t bool)
      |                   ^
string.c:105:7: error: expected expression
  105 |   if (bool)
      |       ^
```